import React from 'react';

const Section = ({ title, children }: { title: string; children: React.ReactNode }) => (
  <div style={styles.section}>
    <h2 style={styles.sectionTitle}>{title}</h2>
    {children}
  </div>
);

const Sub = ({ title, children }: { title: string; children: React.ReactNode }) => (
  <div style={styles.sub}>
    <h3 style={styles.subTitle}>{title}</h3>
    {children}
  </div>
);

const P = ({ children }: { children: React.ReactNode }) => (
  <p style={styles.p}>{children}</p>
);

const UL = ({ items }: { items: (string | React.ReactNode)[] }) => (
  <ul style={styles.ul}>
    {items.map((item, i) => <li key={i} style={styles.li}>{item}</li>)}
  </ul>
);

export default function TermsPage() {
  return (
    <div style={styles.root}>
      <div style={styles.container}>

        <div style={styles.header}>
          <a href="/" style={styles.backLink}>
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
              <path d="M19 12H5M12 19l-7-7 7-7" />
            </svg>
            Back
          </a>
          <h1 style={styles.title}>Terms of Service</h1>
          <p style={styles.subtitle}>Effective: April 13, 2026 &nbsp;·&nbsp; Sandbox Group LLC &nbsp;·&nbsp; Portland, OR</p>
        </div>

        <div style={styles.card}>

          <Section title="1. Introduction">
            <P>These Terms of Service ("Terms") constitute a legally binding agreement between the entity or organization you represent ("Customer," "you," or "your") and Forge Intelligence ("Forge Intelligence," "we," "us," or "our") governing your access to and use of the Forge Intelligence platform, including all related services, APIs, integrations, and documentation (collectively, the "Service").</P>
            <P>By accessing or using the Service, you represent that you have the authority to bind your organization to these Terms. If you do not agree to these Terms, you may not access or use the Service.</P>
          </Section>

          <Section title="2. Definitions">
            <P><strong style={styles.strong}>"Authorized Users"</strong> means the individuals within Customer's organization who are permitted to access and use the Service under Customer's account.</P>
            <P><strong style={styles.strong}>"Brand Profile"</strong> means the compiled data set generated by the Service from a Brand URL scan, deep web research, and AI-powered enrichment, including but not limited to brand voice, messaging, visual identity attributes, audience insights, and competitive positioning data.</P>
            <P><strong style={styles.strong}>"Brand URL"</strong> means the website domain or URL submitted by Customer to the Service for the purpose of generating a Brand Profile.</P>
            <P><strong style={styles.strong}>"Connected Platforms"</strong> means third-party services (such as content management systems, email marketing platforms, social media accounts, and publishing tools) that Customer connects to the Service via OAuth or API integrations for the purpose of distributing Generated Content.</P>
            <P><strong style={styles.strong}>"Customer Data"</strong> means any data, content, or information uploaded, submitted, or otherwise provided by Customer or its Authorized Users to the Service, including Brand URLs, Brand Profiles, and Generated Content.</P>
            <P><strong style={styles.strong}>"Documentation"</strong> means the user guides, help resources, and technical documentation made available by Forge Intelligence describing the features and functionality of the Service.</P>
            <P><strong style={styles.strong}>"Generated Content"</strong> means articles, emails, social media posts, and other content created by the Service's AI content generation tools based on a Brand Profile.</P>
            <P><strong style={styles.strong}>"Order Form"</strong> means any ordering document, subscription confirmation, or online registration that references these Terms and specifies the Service plan, fees, subscription term, and other commercial details.</P>
            <P><strong style={styles.strong}>"Personal Data"</strong> means any information relating to an identified or identifiable natural person, as defined by applicable data protection laws.</P>
            <P><strong style={styles.strong}>"Service"</strong> means the Forge Intelligence cloud-based platform and all associated features, tools, APIs, and integrations, including URL scanning, deep web research, AI-powered brand enrichment, Brand Profile generation, AI content generation, and content publishing through Connected Platforms.</P>
            <P><strong style={styles.strong}>"Subscription Term"</strong> means the period during which Customer has a valid, paid subscription to the Service, as specified in the applicable Order Form.</P>
            <P><strong style={styles.strong}>"Third-Party Brand"</strong> means any brand, company, organization, or entity whose Brand URL is submitted to the Service by Customer or its Authorized Users.</P>
          </Section>

          <Section title="3. Access and Use of the Service">
            <Sub title="3.1 Grant of Access">
              <P>Subject to Customer's compliance with these Terms and payment of all applicable fees, Forge Intelligence grants Customer a non-exclusive, non-transferable, non-sublicensable right to access and use the Service during the Subscription Term solely for Customer's internal business purposes.</P>
            </Sub>
            <Sub title="3.2 Authorized Users">
              <P>Customer may permit its Authorized Users to access the Service in accordance with these Terms. Customer is responsible for all acts and omissions of its Authorized Users and for ensuring that each Authorized User complies with these Terms and the Acceptable Use Policy.</P>
            </Sub>
            <Sub title="3.3 Account Security">
              <P>Customer is responsible for maintaining the confidentiality of its account credentials and for all activity that occurs under its account. Customer shall promptly notify Forge Intelligence of any unauthorized access or use of its account.</P>
            </Sub>
            <Sub title="3.4 Restrictions">
              <P>Customer shall not (and shall not permit any third party to):</P>
              <UL items={[
                "(a) sublicense, sell, lease, or otherwise make the Service available to third parties;",
                "(b) reverse engineer, decompile, disassemble, or otherwise attempt to derive the source code of the Service;",
                "(c) modify, adapt, or create derivative works based on the Service;",
                "(d) copy, frame, or mirror any part of the Service;",
                "(e) access the Service to build a competitive product or service;",
                "(f) use the Service in violation of applicable law or regulation;",
                "(g) interfere with or disrupt the integrity or performance of the Service; or",
                "(h) attempt to gain unauthorized access to the Service or its related systems or networks.",
              ]} />
            </Sub>
          </Section>

          <Section title="4. Brand Authorization and Customer Representations">
            <Sub title="4.1 Proof of Authorization">
              <P>By submitting a Brand URL to the Service, Customer represents and warrants that:</P>
              <UL items={[
                "(a) Customer is the owner of, or an authorized representative of, the Third-Party Brand associated with the Brand URL;",
                "(b) Customer has the legal right and authority to scan, analyze, and extract publicly available information from the Brand URL for the purpose of generating a Brand Profile;",
                "(c) Customer has the legal right and authority to create, publish, and distribute Generated Content on behalf of or in association with the Third-Party Brand;",
                "(d) Customer's use of the Brand URL and any resulting Brand Profile and Generated Content does not violate any agreement, obligation, or duty owed to the Third-Party Brand or any other party; and",
                "(e) Customer has obtained all necessary consents, permissions, and authorizations required to connect any Connected Platforms and publish Generated Content through those platforms on behalf of the Third-Party Brand.",
              ]} />
            </Sub>
            <Sub title="4.2 Ongoing Obligation">
              <P>Customer's authorization representations under Section 4.1 are continuing obligations. If at any time Customer's authority to act on behalf of a Third-Party Brand is revoked, expires, or is otherwise terminated, Customer shall immediately cease using the Service in connection with that Third-Party Brand and promptly notify Forge Intelligence.</P>
            </Sub>
            <Sub title="4.3 Documentation of Authorization">
              <P>Forge Intelligence reserves the right to request reasonable documentation demonstrating Customer's authorization to act on behalf of any Third-Party Brand at any time. Customer shall provide such documentation within ten (10) business days of the request. Failure to provide adequate documentation may result in suspension of the Service with respect to the affected Brand Profile.</P>
            </Sub>
          </Section>

          <Section title="5. Verification and Dispute Process">
            <Sub title="5.1 Third-Party Brand Disputes">
              <P>If a Third-Party Brand owner or its authorized representative ("Claimant") contacts Forge Intelligence to dispute Customer's authorization to use its Brand URL, Brand Profile, or Generated Content, the following process shall apply:</P>
            </Sub>
            <Sub title="5.2 Notice to Customer">
              <P>Forge Intelligence will promptly notify Customer of the dispute and provide Customer with the substance of the Claimant's allegations. Customer shall have ten (10) business days from receipt of such notice to respond with evidence of authorization.</P>
            </Sub>
            <Sub title="5.3 Interim Measures">
              <P>Upon receipt of a dispute that Forge Intelligence determines to be facially credible, Forge Intelligence may, in its sole discretion:</P>
              <UL items={[
                "(a) Suspend the generation, publication, or distribution of new Generated Content associated with the disputed Brand Profile;",
                "(b) Suspend public access to existing Generated Content associated with the disputed Brand Profile through Connected Platforms, to the extent technically feasible; and",
                "(c) Restrict Customer's ability to modify or export the disputed Brand Profile.",
              ]} />
              <P>Such interim measures are protective in nature and do not constitute a determination of the merits of the dispute.</P>
            </Sub>
            <Sub title="5.4 Resolution">
              <UL items={[
                <><strong style={styles.strong}>(a) Authorization Confirmed:</strong> If Customer provides adequate evidence of authorization within the response period, Forge Intelligence will lift any interim measures and restore full access.</>,
                <><strong style={styles.strong}>(b) Authorization Not Confirmed:</strong> If Customer fails to respond, fails to provide adequate evidence, or if the Claimant provides compelling evidence that Customer lacks authorization, Forge Intelligence may permanently disable the disputed Brand Profile, remove or disable associated Generated Content, and terminate Customer's access to the Service with respect to the affected Third-Party Brand.</>,
                <><strong style={styles.strong}>(c) Disputed Claims:</strong> If the evidence is inconclusive, Forge Intelligence may maintain interim measures and require the parties to resolve the dispute directly. Forge Intelligence is not obligated to adjudicate disputes between Customer and any Claimant.</>,
              ]} />
            </Sub>
            <Sub title="5.5 No Liability for Good-Faith Enforcement">
              <P>Forge Intelligence shall not be liable to Customer for any loss, damage, or disruption arising from good-faith enforcement of this Section 5, including the suspension or removal of Brand Profiles or Generated Content.</P>
            </Sub>
          </Section>

          <Section title="6. Customer Data">
            <Sub title="6.1 Ownership">
              <P>Customer retains all right, title, and interest in and to Customer Data. Nothing in these Terms transfers ownership of Customer Data to Forge Intelligence.</P>
            </Sub>
            <Sub title="6.2 License to Customer Data">
              <P>Customer grants Forge Intelligence a non-exclusive, worldwide license to use, process, and store Customer Data solely to the extent necessary to provide, maintain, and improve the Service in accordance with these Terms.</P>
            </Sub>
            <Sub title="6.3 Data Processing">
              <P>To the extent Forge Intelligence processes Personal Data on behalf of Customer, the parties shall enter into a Data Processing Agreement ("DPA"), which shall be incorporated into and form part of these Terms.</P>
            </Sub>
            <Sub title="6.4 Data Security">
              <P>Forge Intelligence shall implement and maintain commercially reasonable administrative, technical, and organizational security measures designed to protect Customer Data against unauthorized access, loss, alteration, or destruction. Details of Forge Intelligence's security practices are described in the Documentation.</P>
            </Sub>
            <Sub title="6.5 Data Retention and Deletion">
              <P>Upon termination or expiration of the Subscription Term, Customer may request the return or deletion of its Customer Data. Forge Intelligence shall comply with such request within thirty (30) days, except to the extent that applicable law requires retention.</P>
            </Sub>
          </Section>

          <Section title="7. Fees and Payment">
            <Sub title="7.1 Fees">
              <P>Customer agrees to pay all fees specified in the applicable Order Form. Unless otherwise stated in an Order Form, all fees are quoted in U.S. dollars and are non-refundable.</P>
            </Sub>
            <Sub title="7.2 Invoicing and Payment Terms">
              <P>Forge Intelligence will invoice Customer in accordance with the billing frequency stated in the Order Form. Payment is due within thirty (30) days of the invoice date unless otherwise specified.</P>
            </Sub>
            <Sub title="7.3 Taxes">
              <P>All fees are exclusive of taxes. Customer is responsible for paying any applicable sales, use, VAT, or similar taxes, excluding taxes based on Forge Intelligence's net income.</P>
            </Sub>
            <Sub title="7.4 Late Payments">
              <P>If Customer fails to make timely payment, Forge Intelligence may charge interest on overdue amounts at a rate of 1.5% per month (or the maximum rate permitted by law, whichever is less) and may suspend access to the Service upon fifteen (15) days' written notice of non-payment.</P>
            </Sub>
          </Section>

          <Section title="8. Proprietary Rights">
            <Sub title="8.1 Forge Intelligence IP">
              <P>Forge Intelligence owns all right, title, and interest in and to the Service, including all software, algorithms, models, interfaces, Documentation, trademarks, and other intellectual property. These Terms do not grant Customer any rights to Forge Intelligence's intellectual property except the limited access right described in Section 3.1.</P>
            </Sub>
            <Sub title="8.2 Feedback">
              <P>If Customer provides Forge Intelligence with suggestions, enhancement requests, or other feedback regarding the Service ("Feedback"), Forge Intelligence may freely use, incorporate, and commercialize such Feedback without obligation or compensation to Customer.</P>
            </Sub>
          </Section>

          <Section title="9. Confidentiality">
            <Sub title="9.1 Definition">
              <P>"Confidential Information" means any non-public information disclosed by one party to the other in connection with these Terms that is designated as confidential or that reasonably should be understood to be confidential given the nature of the information and the circumstances of disclosure. Confidential Information includes, without limitation, Customer Data, business plans, pricing, and technical information.</P>
            </Sub>
            <Sub title="9.2 Obligations">
              <P>Each party agrees to: (a) use the other party's Confidential Information solely for the purposes of performing its obligations under these Terms; (b) not disclose Confidential Information to third parties except to employees, contractors, and advisors who have a need to know and are bound by obligations of confidentiality at least as protective as those in this Section; and (c) protect Confidential Information using at least the same degree of care it uses for its own confidential information, but in no event less than reasonable care.</P>
            </Sub>
            <Sub title="9.3 Exceptions">
              <P>Confidential Information does not include information that: (a) is or becomes publicly available through no fault of the receiving party; (b) was already known to the receiving party without restriction; (c) is independently developed by the receiving party without use of the disclosing party's Confidential Information; or (d) is received from a third party without restriction and without breach of any obligation of confidentiality.</P>
            </Sub>
            <Sub title="9.4 Compelled Disclosure">
              <P>If a party is compelled by law to disclose Confidential Information, it shall provide the other party with prompt written notice (to the extent legally permitted) and shall disclose only the minimum information required.</P>
            </Sub>
          </Section>

          <Section title="10. Representations and Warranties">
            <Sub title="10.1 Mutual Representations">
              <P>Each party represents and warrants that: (a) it has the legal power and authority to enter into these Terms; and (b) it will comply with all applicable laws in its performance under these Terms.</P>
            </Sub>
            <Sub title="10.2 Service Warranty">
              <P>Forge Intelligence warrants that the Service will perform materially in accordance with the Documentation during the Subscription Term. Customer's sole remedy for breach of this warranty is, at Forge Intelligence's option, correction of the non-conforming Service or termination of the affected subscription with a pro-rata refund of prepaid fees.</P>
            </Sub>
            <Sub title="10.3 Disclaimer">
              <P><strong style={styles.strong}>EXCEPT AS EXPRESSLY SET FORTH IN THIS SECTION 10, THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE." FORGE INTELLIGENCE DISCLAIMS ALL OTHER WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT. FORGE INTELLIGENCE DOES NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF HARMFUL COMPONENTS.</strong></P>
            </Sub>
            <Sub title="10.4 Disclaimer of Responsibility for Generated Content and Brand Activity">
              <P>Forge Intelligence is a neutral technology platform. Customer acknowledges and agrees that:</P>
              <UL items={[
                <><strong style={styles.strong}>No Endorsement.</strong> Forge Intelligence does not endorse, approve, or verify the accuracy, completeness, legality, or appropriateness of any Generated Content, Brand Profile, or content published through Connected Platforms. The inclusion of any Third-Party Brand on the Service does not imply any affiliation, sponsorship, or endorsement by or between Forge Intelligence and that Third-Party Brand.</>,
                <><strong style={styles.strong}>No Alignment with Brand Values.</strong> Forge Intelligence is an independent technology provider and does not adopt, represent, or align itself with the values, opinions, positions, or public statements of any Third-Party Brand whose Brand URL is processed through the Service.</>,
                <><strong style={styles.strong}>Customer Responsibility.</strong> Customer is solely responsible for reviewing, approving, and assuming liability for all Generated Content before publication or distribution. Forge Intelligence provides AI-powered content generation tools, but the decision to publish and the content as published are Customer's sole responsibility.</>,
                <><strong style={styles.strong}>No Guarantee of Accuracy.</strong> Brand Profiles are generated through automated URL scanning, deep web research, and AI enrichment processes. Forge Intelligence does not guarantee the accuracy, completeness, or timeliness of the data contained in any Brand Profile. Customer is responsible for verifying the accuracy of Brand Profiles and Generated Content.</>,
                <><strong style={styles.strong}>Third-Party Platform Compliance.</strong> Forge Intelligence is not responsible for ensuring that Generated Content complies with the terms of service, community guidelines, or policies of any Connected Platform. Customer is solely responsible for compliance with the terms of any third-party platforms to which Generated Content is published.</>,
              ]} />
            </Sub>
            <Sub title="10.5 Data Privacy Framework">
              <P>Forge Intelligence participates in the EU-U.S. Data Privacy Framework, the UK Extension to the EU-U.S. Data Privacy Framework, and the Swiss-U.S. Data Privacy Framework (collectively, the "Data Privacy Framework") as set forth by the U.S. Department of Commerce. Forge Intelligence's compliance with the Data Privacy Framework is subject to the limitations and conditions described in our Privacy Policy and Data Processing Agreement. Nothing in these Terms expands or modifies Forge Intelligence's obligations under the Data Privacy Framework beyond what is required by the applicable framework principles.</P>
            </Sub>
          </Section>

          <Section title="11. Indemnification">
            <Sub title="11.1 By Forge Intelligence">
              <P>Forge Intelligence shall defend, indemnify, and hold harmless Customer from and against any third-party claim alleging that the Service, as provided by Forge Intelligence, infringes or misappropriates any third party's intellectual property rights, and shall pay any damages finally awarded or settlement amounts approved in writing by Forge Intelligence. This obligation does not apply to the extent a claim arises from: (a) Customer Data; (b) modifications to the Service not made by Forge Intelligence; (c) combination of the Service with third-party products or services; or (d) use of the Service in violation of these Terms.</P>
            </Sub>
            <Sub title="11.2 By Customer — General">
              <P>Customer shall defend, indemnify, and hold harmless Forge Intelligence, its officers, directors, employees, and agents from and against any third-party claim arising from: (a) Customer Data; (b) Customer's use of the Service in violation of these Terms or applicable law; or (c) Customer's breach of its obligations under these Terms.</P>
            </Sub>
            <Sub title="11.3 By Customer — Brand Authorization">
              <P>Without limiting Section 11.2, Customer shall defend, indemnify, and hold harmless Forge Intelligence, its officers, directors, employees, and agents from and against any and all claims, demands, lawsuits, damages, losses, liabilities, costs, and expenses (including reasonable attorneys' fees and litigation costs) arising from or related to:</P>
              <UL items={[
                "(a) Customer's submission of a Brand URL for which Customer lacked proper authorization;",
                "(b) The creation, publication, or distribution of Generated Content on behalf of a Third-Party Brand without proper authorization;",
                "(c) Any claim by a Third-Party Brand or its representative that Customer's use of the Service infringed, misappropriated, or violated its intellectual property rights, trademark rights, publicity rights, or other proprietary rights;",
                "(d) Customer's breach of its representations and warranties under Section 4 (Brand Authorization and Customer Representations); or",
                "(e) Any claim that Generated Content published through Connected Platforms on behalf of a Third-Party Brand was misleading, defamatory, or otherwise harmful.",
              ]} />
              <P>This indemnification obligation survives termination or expiration of these Terms and applies regardless of whether Forge Intelligence was negligent in failing to detect or prevent the unauthorized activity. Customer's obligation under this Section is not subject to the limitation of liability in Section 12.</P>
            </Sub>
          </Section>

          <Section title="12. Limitation of Liability">
            <Sub title="12.1 Cap on Liability">
              <P><strong style={styles.strong}>EXCEPT FOR EACH PARTY'S INDEMNIFICATION OBLIGATIONS UNDER SECTION 11 AND BREACHES OF SECTION 9 (CONFIDENTIALITY), NEITHER PARTY'S AGGREGATE LIABILITY UNDER THESE TERMS SHALL EXCEED THE TOTAL FEES PAID OR PAYABLE BY CUSTOMER IN THE TWELVE (12) MONTHS PRECEDING THE EVENT GIVING RISE TO THE CLAIM.</strong></P>
            </Sub>
            <Sub title="12.2 Exclusion of Consequential Damages">
              <P><strong style={styles.strong}>IN NO EVENT SHALL EITHER PARTY BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR DAMAGES FOR LOSS OF PROFITS, REVENUE, DATA, OR BUSINESS OPPORTUNITY, REGARDLESS OF THE THEORY OF LIABILITY, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</strong></P>
            </Sub>
            <Sub title="12.3 Applicability">
              <P>The limitations in this Section 12 shall apply to the maximum extent permitted by applicable law.</P>
            </Sub>
          </Section>

          <Section title="13. Term and Termination">
            <Sub title="13.1 Term">
              <P>These Terms commence on the date Customer first accesses the Service and continue until all Subscription Terms have expired or been terminated.</P>
            </Sub>
            <Sub title="13.2 Subscription Renewal">
              <P>Unless otherwise specified in an Order Form, subscriptions automatically renew for successive periods equal to the initial Subscription Term unless either party provides written notice of non-renewal at least thirty (30) days before the end of the then-current term.</P>
            </Sub>
            <Sub title="13.3 Termination for Cause">
              <P>Either party may terminate these Terms (or any Order Form) upon written notice if the other party: (a) materially breaches these Terms and fails to cure such breach within thirty (30) days of receiving written notice; or (b) becomes subject to bankruptcy, insolvency, or similar proceedings. For violations of the Acceptable Use Policy, the notice and enforcement process set forth in the AUP shall govern.</P>
            </Sub>
            <Sub title="13.4 Termination for Convenience">
              <P>Either party may terminate a Subscription Term for convenience upon sixty (60) days' prior written notice. If Customer terminates for convenience, no refund of prepaid fees shall be owed.</P>
            </Sub>
            <Sub title="13.5 Effect of Termination">
              <P>Upon termination or expiration: (a) Customer's access to the Service shall cease; (b) each party shall return or destroy the other party's Confidential Information upon request; and (c) Sections 4 (Brand Authorization), 5 (Verification and Dispute Process), 6 (Customer Data), 8 (Proprietary Rights), 9 (Confidentiality), 10.4 (Disclaimer of Responsibility), 11 (Indemnification), 12 (Limitation of Liability), 14 (Dispute Resolution), and 15 (General Provisions) shall survive.</P>
            </Sub>
          </Section>

          <Section title="14. Dispute Resolution">
            <Sub title="14.1 Governing Law">
              <P>These Terms shall be governed by and construed in accordance with the laws of the State of Oregon, without regard to its conflict of laws principles.</P>
            </Sub>
            <Sub title="14.2 Arbitration">
              <P>Any dispute arising out of or relating to these Terms shall be resolved by binding arbitration administered by the American Arbitration Association under its Commercial Arbitration Rules. The arbitration shall take place in Portland, Oregon. Judgment on the arbitration award may be entered in any court of competent jurisdiction.</P>
            </Sub>
            <Sub title="14.3 Injunctive Relief">
              <P>Notwithstanding the foregoing, either party may seek injunctive or other equitable relief in any court of competent jurisdiction to protect its intellectual property rights or Confidential Information.</P>
            </Sub>
          </Section>

          <Section title="15. General Provisions">
            <Sub title="15.1 Entire Agreement">
              <P>These Terms, together with all Order Forms, the <a href="/acceptable-use" style={styles.link}>Acceptable Use Policy</a>, and the DPA (if applicable), constitute the entire agreement between the parties regarding the subject matter hereof and supersede all prior agreements, proposals, and representations.</P>
            </Sub>
            <Sub title="15.2 Amendments">
              <P>Forge Intelligence may update these Terms from time to time. Material changes will be communicated to Customer at least thirty (30) days before they take effect. Continued use of the Service after such notice constitutes acceptance of the updated Terms.</P>
            </Sub>
            <Sub title="15.3 Assignment">
              <P>Neither party may assign these Terms without the other party's prior written consent, except that either party may assign these Terms in connection with a merger, acquisition, or sale of all or substantially all of its assets.</P>
            </Sub>
            <Sub title="15.4 Notices">
              <P>All notices under these Terms shall be in writing and sent to the addresses specified in the applicable Order Form or to such other address as a party may designate in writing.</P>
            </Sub>
            <Sub title="15.5 Severability">
              <P>If any provision of these Terms is held to be invalid or unenforceable, the remaining provisions shall continue in full force and effect.</P>
            </Sub>
            <Sub title="15.6 Waiver">
              <P>No failure or delay by either party in exercising any right under these Terms shall operate as a waiver of that right.</P>
            </Sub>
            <Sub title="15.7 Force Majeure">
              <P>Neither party shall be liable for any failure or delay in performance due to causes beyond its reasonable control, including acts of God, natural disasters, pandemic, war, terrorism, labor disputes, or government actions.</P>
            </Sub>
            <Sub title="15.8 Independent Contractors">
              <P>The parties are independent contractors. Nothing in these Terms creates a partnership, joint venture, or agency relationship.</P>
            </Sub>
          </Section>

          <div style={{ textAlign: 'center', paddingTop: 16, color: '#64748B', fontSize: 13 }}>
            <P>Sandbox Group LLC &nbsp;·&nbsp; Portland, Oregon &nbsp;·&nbsp; <a href="mailto:hello@forgeintelligence.ai" style={styles.link}>hello@forgeintelligence.ai</a> &nbsp;·&nbsp; <a href="https://forgeintelligence.ai" style={styles.link}>forgeintelligence.ai</a></P>
          </div>

        </div>
      </div>
    </div>
  );
}

const styles: Record<string, React.CSSProperties> = {
  root: {
    minHeight: '100vh',
    backgroundColor: '#0B0F1A',
    color: '#F8FAFC',
    fontFamily: "Inter, 'Geist', system-ui, -apple-system, sans-serif",
    padding: '80px 24px',
  },
  container: {
    maxWidth: 760,
    margin: '0 auto',
    width: '100%',
  },
  header: {
    marginBottom: 48,
  },
  backLink: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    color: '#64748B',
    textDecoration: 'none',
    fontSize: 14,
    marginBottom: 32,
  },
  title: {
    fontSize: 36,
    fontWeight: 700,
    color: '#F8FAFC',
    margin: '0 0 8px',
    letterSpacing: '-0.5px',
  },
  subtitle: {
    fontSize: 13,
    color: '#64748B',
    margin: 0,
  },
  card: {
    backgroundColor: '#1E293B',
    borderRadius: 12,
    border: '1px solid rgba(255,255,255,0.06)',
    padding: '48px 52px',
  },
  section: {
    marginBottom: 40,
    paddingBottom: 40,
    borderBottom: '1px solid rgba(255,255,255,0.06)',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 600,
    color: '#F8FAFC',
    margin: '0 0 16px',
    letterSpacing: '-0.2px',
  },
  sub: {
    marginBottom: 20,
  },
  subTitle: {
    fontSize: 14,
    fontWeight: 600,
    color: '#CBD5E1',
    margin: '0 0 8px',
  },
  p: {
    fontSize: 15,
    color: '#94A3B8',
    lineHeight: 1.75,
    margin: '0 0 12px',
  },
  ul: {
    margin: '0 0 12px',
    paddingLeft: 20,
  },
  li: {
    fontSize: 15,
    color: '#94A3B8',
    lineHeight: 1.75,
    marginBottom: 8,
  },
  strong: {
    color: '#CBD5E1',
    fontWeight: 600,
  },
  link: {
    color: '#3563FF',
    textDecoration: 'none',
  },
};
